pipeline {
    // --> install awscli, docker,kubectl
    agent any  
    // agent {
    //     docker {
    //         image 'node:lts-buster-slim'
    //         args '-p 4000:3000'
    //     }
    // }
    environment {
        DOCKER_REGISTRY = 'arshad200'
        DOCKER_IMAGE = "${DOCKER_REGISTRY}/react_with_node"
        DOCKER_CREDENTIALS_ID = 'docker-hub-credentials'
         
    }
    stages {
        stage('Checkout Code') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'GitPAT', usernameVariable: 'GIT_USERNAME', passwordVariable: 'GIT_PASSWORD')]) {
                    sh 'git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/Arshu200/EKS-Using-Terraform.git'
                }
            }
        }
        stage('Docker Build') {
            steps {
                script {
                    
                    sh 'docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }
        stage('Publish to DockerHub') {
            steps {
                 script {
                    docker.withRegistry('', DOCKER_CREDENTIALS_ID) {
                        docker.image("${DOCKER_IMAGE}:${env.BUILD_ID}").push()
                        // docker.image("${DOCKER_IMAGE}:${env.BUILD_ID}").push('latest')+++
                    }
                }
            }
        }
        stage('Deploy to EKS') {
            steps {
                script {
                    sh 'aws eks update-kubeconfig --name=Terraform-Cluster --region=us-east-1'
                    sh '''
                    sed -i 's#__IMAGE_TAG__#${env.BUILD_ID}#g' k8s_manifest/deployment.yaml
                    '''
                    sh 'kubectl apply -f k8s_manifest/namespace.yaml'
                    sh 'kubectl apply -f k8s_manifest/deployment.yaml'
                    sh 'kubectl apply -f k8s_manifest/service.yaml'
                }
            }
        }
        stage('Send Notification') {
            steps {
                mail to: 'arshad22shaik@gmail.com',
                    subject: "Build ${env.BUILD_NUMBER} - ${currentBuild.currentResult} React App was Succesfull!",
                    body: "The sample-node-js-React-npm-app was successfull \n\nBuild ${env.BUILD_NUMBER} is complete. \n\nStatus: ${currentBuild.currentResult}"
            }
        }
    }
    post {
        always {
            cleanWs() 
        }
    }
}
